name = "Privacy Hermit"
license = "MIT"
licenselink = "https://github.com/nodeg/prv-hermit/blob/master/LICENSE"
description = "A minimal and fast hugo theme with privacy in mind."
homepage = "https://github.com/nodeg/prv-hermit"
tags = ["blog", "minimal", "dark", "responsive", "privact"]
features = [
  "single column",
  "featured image",
  "social icons",
  "disqus"
]
min_version = 0.43

[author]
  name = "Dominik Gedon"
  homepage = "https://gedon.org"

[original]
  name = "Track3"
  homepage = "https://www.xxxlbox.com"
  repo = "https://github.com/Track3/hermit"