name: Linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1.312.0
      with:
        ruby-version: '4.0'
    - name: Install dependencies
      run:  gem install mdl
    - name: Run markdownlint
      run:  mdl -c .mdlrc content/post/
